######################################################

#  Student Name: Eddie Wenker

#  Course Code: CSCI 460 -- Fall 2026

#  Assignment Due Date: 10/25/26

#  GitHub Link: (https://github.com/Wenker-ed/CSCI-460-Programming-Assignment-I)

######################################################

In [ ]:
import pandas as pd
# import performance metric libraries
from sklearn.metrics import (
accuracy_score,
confusion_matrix,
ConfusionMatrixDisplay,
f1_score,
classification_report,
)

In [4]:
df = pd.read_csv('bank-full.csv', delimiter=';')

In [5]:
df.head() #The data is related with direct marketing campaigns of a Portuguese banking institution. 
#The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required,
# in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed.

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [15]:
#map all categorical variables to integers
d = {"yes":1,"no":0} # list integer values for each label in d
df['loan'] = df['loan'].map(d) # map d on all rows of df[‘loan’]

In [16]:
df['job'] = df['job'].map({'admin.': 0, 'blue-collar': 1, 'entrepreneur': 2, 'housemaid': 3, 'management': 4, 'retired': 5, 'self-employed': 6, 'services': 7, 'student': 8, 'technician': 9, 'unemployed': 10, 'unknown': 11})
df['marital'] = df['marital'].map({'divorced': 0, 'married': 1, 'single': 2, 'unknown': 3})
df['education'] = df['education'].map({'basic.4y': 0, 'basic.6y': 1, 'basic.9y': 2, 'high.school': 3, 'illiterate': 4, 'professional.course': 5, 'university.degree': 6, 'unknown': 7})

In [17]:
df['default'] = df['default'].map({'yes': 1, 'no': 0})
df['housing'] = df['housing'].map({'yes': 1, 'no': 0})
df['contact'] = df['contact'].map({'cellular': 0, 'telephone': 1, 'unknown': 2})
df['month'] = df['month'].map({'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6, 'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12})

In [18]:
df['poutcome'] = df['poutcome'].map({'failure': 0, 'success': 1, 'unknown': 2})
df['y'] = df['y'].map({'yes': 1, 'no': 0})

In [19]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,4,1,NaN,0,2143,1,0,2,5,5,261,1,-1,0,2.0,0
1,44,9,2,NaN,0,29,1,0,2,5,5,151,1,-1,0,2.0,0
2,33,2,1,NaN,0,2,1,1,2,5,5,76,1,-1,0,2.0,0
3,47,1,1,7.0,0,1506,1,0,2,5,5,92,1,-1,0,2.0,0
4,33,11,2,7.0,0,1,0,0,2,5,5,198,1,-1,0,2.0,0

In [20]:
df.shape

(45211, 17)

In [21]:
df.dropna(inplace=True)

In [22]:
df.shape

(1792, 17)

In [24]:
x = df.drop(columns=['y'])
y = df['y']

In [26]:
x.shape

(1792, 16)

In [27]:
y.shape

(1792,)

In [23]:


# measure the performance
accuracy = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")
print("The accuracy of my Naive Bayes Model is:", accuracy)
print("The F1 Score of my Naive Bayes Model is:", f1)

NameError: name 'y_pred' is not defined